/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinema;

import javax.swing.JFileChooser;
import javax.swing.JFrame;

/**
 *
 * @author SuPeR_FaNtASy
 */
public class NewMovie extends javax.swing.JFrame {
static String cvp;
    public NewMovie() {
        initComponents();
        this.setSize(726, 288);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titletxt = new javax.swing.JTextField();
        directortxt = new javax.swing.JTextField();
        yeartxt = new javax.swing.JTextField();
        pricetxt = new javax.swing.JTextField();
        Browse = new javax.swing.JButton();
        update = new javax.swing.JButton();
        hallid4 = new javax.swing.JLabel();
        hallid5 = new javax.swing.JLabel();
        hallid6 = new javax.swing.JLabel();
        hallid7 = new javax.swing.JLabel();
        minm = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        titlebar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        titletxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        titletxt.setForeground(new java.awt.Color(255, 255, 255));
        titletxt.setText("title");
        titletxt.setOpaque(false);
        getContentPane().add(titletxt);
        titletxt.setBounds(20, 140, 140, 40);

        directortxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        directortxt.setForeground(new java.awt.Color(255, 255, 255));
        directortxt.setText("director");
        directortxt.setOpaque(false);
        getContentPane().add(directortxt);
        directortxt.setBounds(210, 140, 160, 40);

        yeartxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        yeartxt.setForeground(new java.awt.Color(255, 255, 255));
        yeartxt.setText("2016");
        yeartxt.setOpaque(false);
        getContentPane().add(yeartxt);
        yeartxt.setBounds(420, 140, 100, 40);

        pricetxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        pricetxt.setForeground(new java.awt.Color(255, 255, 255));
        pricetxt.setText("20");
        pricetxt.setOpaque(false);
        getContentPane().add(pricetxt);
        pricetxt.setBounds(590, 140, 90, 40);

        Browse.setBackground(new java.awt.Color(0, 0, 0));
        Browse.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Browse.setForeground(new java.awt.Color(255, 255, 255));
        Browse.setText("Browse");
        Browse.setOpaque(false);
        Browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseActionPerformed(evt);
            }
        });
        getContentPane().add(Browse);
        Browse.setBounds(240, 230, 110, 34);

        update.setBackground(new java.awt.Color(0, 0, 0));
        update.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("insert");
        update.setOpaque(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(380, 230, 110, 34);

        hallid4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        hallid4.setForeground(new java.awt.Color(255, 255, 255));
        hallid4.setText("title");
        getContentPane().add(hallid4);
        hallid4.setBounds(40, 60, 130, 30);

        hallid5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        hallid5.setForeground(new java.awt.Color(255, 255, 255));
        hallid5.setText("director");
        getContentPane().add(hallid5);
        hallid5.setBounds(230, 60, 140, 30);

        hallid6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        hallid6.setForeground(new java.awt.Color(255, 255, 255));
        hallid6.setText("year");
        getContentPane().add(hallid6);
        hallid6.setBounds(440, 60, 80, 30);

        hallid7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        hallid7.setForeground(new java.awt.Color(255, 255, 255));
        hallid7.setText("price");
        getContentPane().add(hallid7);
        hallid7.setBounds(600, 70, 80, 30);

        minm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinema/img/min.png"))); // NOI18N
        minm.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        minm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minmMouseClicked(evt);
            }
        });
        getContentPane().add(minm);
        minm.setBounds(670, 0, 33, 30);

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinema/img/close.png"))); // NOI18N
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        getContentPane().add(close);
        close.setBounds(700, 0, 30, 30);

        titlebar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinema/img/title.png"))); // NOI18N
        titlebar.setCursor(new java.awt.Cursor(java.awt.Cursor.SE_RESIZE_CURSOR));
        titlebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titlebarMouseDragged(evt);
            }
        });
        titlebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titlebarMousePressed(evt);
            }
        });
        getContentPane().add(titlebar);
        titlebar.setBounds(-20, 0, 1450, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinema/img/bk.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-190, 0, 1180, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseActionPerformed
        JFileChooser j=new  JFileChooser();
        j.showOpenDialog(j);

        cvp =j.getSelectedFile().getName().replace(".png","");
        System.out.println(cvp);
    }//GEN-LAST:event_BrowseActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        
        Movie nn=new Movie(1000, titletxt.getText(), directortxt.getText(), Integer.parseInt(pricetxt.getText()), Integer.parseInt(yeartxt.getText()),cvp);
Moviepanel.admin();
this.setVisible(false);new Box("movie added",0);
    }//GEN-LAST:event_updateActionPerformed
int x,y;
    private void titlebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlebarMouseDragged
        this.setLocation(evt.getXOnScreen()-x,evt.getYOnScreen()-y);
    }//GEN-LAST:event_titlebarMouseDragged

    private void titlebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlebarMousePressed
        x=evt.getX();y=evt.getY();
    }//GEN-LAST:event_titlebarMousePressed

    private void minmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minmMouseClicked
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minmMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_closeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewMovie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton Browse;
    private javax.swing.JLabel close;
    private static javax.swing.JTextField directortxt;
    private static javax.swing.JLabel hallid4;
    private static javax.swing.JLabel hallid5;
    private static javax.swing.JLabel hallid6;
    private static javax.swing.JLabel hallid7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel minm;
    private static javax.swing.JTextField pricetxt;
    private javax.swing.JLabel titlebar;
    private static javax.swing.JTextField titletxt;
    private static javax.swing.JButton update;
    private static javax.swing.JTextField yeartxt;
    // End of variables declaration//GEN-END:variables
}
