/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinema;

import javax.swing.JFrame;

/**
 *
 * @author SuPeR_FaNtASy
 */
public class NewTime extends javax.swing.JFrame {

    Movie movie;
    public NewTime(Movie movie) {
        this.movie=movie;
        initComponents();
        this.setSize(728, 214);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hallid4 = new javax.swing.JLabel();
        hallid5 = new javax.swing.JLabel();
        hallid6 = new javax.swing.JLabel();
        hallid7 = new javax.swing.JLabel();
        pricetxt = new javax.swing.JTextField();
        yeartxt = new javax.swing.JTextField();
        directortxt = new javax.swing.JTextField();
        titletxt = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        minm = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        titlebar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        hallid4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        hallid4.setForeground(new java.awt.Color(255, 255, 255));
        hallid4.setText("hall");
        getContentPane().add(hallid4);
        hallid4.setBounds(40, 60, 130, 30);

        hallid5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        hallid5.setForeground(new java.awt.Color(255, 255, 255));
        hallid5.setText("date");
        getContentPane().add(hallid5);
        hallid5.setBounds(180, 60, 140, 30);

        hallid6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        hallid6.setForeground(new java.awt.Color(255, 255, 255));
        hallid6.setText("start");
        getContentPane().add(hallid6);
        hallid6.setBounds(360, 60, 80, 30);

        hallid7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        hallid7.setForeground(new java.awt.Color(255, 255, 255));
        hallid7.setText("end");
        getContentPane().add(hallid7);
        hallid7.setBounds(490, 60, 80, 30);

        pricetxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        pricetxt.setForeground(new java.awt.Color(255, 255, 255));
        pricetxt.setText("06:59");
        pricetxt.setOpaque(false);
        getContentPane().add(pricetxt);
        pricetxt.setBounds(470, 140, 90, 40);

        yeartxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        yeartxt.setForeground(new java.awt.Color(255, 255, 255));
        yeartxt.setText("05:10");
        yeartxt.setOpaque(false);
        getContentPane().add(yeartxt);
        yeartxt.setBounds(350, 140, 100, 40);

        directortxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        directortxt.setForeground(new java.awt.Color(255, 255, 255));
        directortxt.setText("2016-04-17");
        directortxt.setOpaque(false);
        getContentPane().add(directortxt);
        directortxt.setBounds(170, 140, 160, 40);

        titletxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        titletxt.setForeground(new java.awt.Color(255, 255, 255));
        titletxt.setText("hall");
        titletxt.setOpaque(false);
        getContentPane().add(titletxt);
        titletxt.setBounds(20, 140, 140, 40);

        update.setBackground(new java.awt.Color(0, 0, 0));
        update.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("insert");
        update.setOpaque(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(580, 140, 110, 40);

        minm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinema/img/min.png"))); // NOI18N
        minm.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        minm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minmMouseClicked(evt);
            }
        });
        getContentPane().add(minm);
        minm.setBounds(670, 0, 33, 30);

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinema/img/close.png"))); // NOI18N
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        getContentPane().add(close);
        close.setBounds(700, 0, 30, 30);

        titlebar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinema/img/title.png"))); // NOI18N
        titlebar.setCursor(new java.awt.Cursor(java.awt.Cursor.SE_RESIZE_CURSOR));
        titlebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titlebarMouseDragged(evt);
            }
        });
        titlebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titlebarMousePressed(evt);
            }
        });
        getContentPane().add(titlebar);
        titlebar.setBounds(-20, 0, 1450, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinema/img/bk.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-190, 0, 1180, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
Time c=new Time();
if(c.checkTime(Integer.parseInt(yeartxt.getText().substring(0,2)),Integer.parseInt(pricetxt.getText().substring(0,2)) ,directortxt.getText(),Integer.parseInt(titletxt.getText()))){
        Time n=new Time(1000,movie.getId(),directortxt.getText()+" 00:00:00.000000","1899-12-30 "+yeartxt.getText()+":00.000000","1899-12-30 "+pricetxt.getText()+":00.000000",Integer.parseInt(titletxt.getText()));
        TimeFrame.admin();
        this.setVisible(false);new Box("TimeAdded",0);}
else {new Box("a movie within the given time alredy exist");}
    }//GEN-LAST:event_updateActionPerformed
int x,y;
    private void titlebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlebarMouseDragged
        this.setLocation(evt.getXOnScreen()-x,evt.getYOnScreen()-y);
    }//GEN-LAST:event_titlebarMouseDragged

    private void titlebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlebarMousePressed
        x=evt.getX();y=evt.getY();
    }//GEN-LAST:event_titlebarMousePressed

    private void minmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minmMouseClicked
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minmMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_closeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new NewTime().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close;
    private static javax.swing.JTextField directortxt;
    private static javax.swing.JLabel hallid4;
    private static javax.swing.JLabel hallid5;
    private static javax.swing.JLabel hallid6;
    private static javax.swing.JLabel hallid7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel minm;
    private static javax.swing.JTextField pricetxt;
    private javax.swing.JLabel titlebar;
    private static javax.swing.JTextField titletxt;
    private static javax.swing.JButton update;
    private static javax.swing.JTextField yeartxt;
    // End of variables declaration//GEN-END:variables
}
