/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinema;

/**
 *
 * @author SuPeR_FaNtASy
 */
public class SAtime extends javax.swing.JPanel {

    Movie movie;
    Time time;
    String st1,nd1,st,dt,nd;
    public SAtime(Time te,Movie me) {
        this.time=te;
        this.movie=me;
        initComponents();
        
      hall.setText(""+this.time.getHallId()+"");
        date.setText(time.getMovieDate().substring(0, 10));
        end.setText(time.getMovieEnd().substring(11,16));
        start.setText(time.getMovieStart().substring(11,16));
        
        dt=time.getMovieStart().substring(10);
        st=time.getMovieStart().substring(0, 11);st1=time.getMovieStart().substring(16);
        nd=time.getMovieEnd().substring(0, 11);nd1=time.getMovieEnd().substring(16);
        Ticket t= new Ticket();
      seats.setText(t.count(te.getId())+"");
        
    }

    public SAtime() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        end = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        seats = new javax.swing.JLabel();
        start = new javax.swing.JTextField();
        hall = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        update.setBackground(new java.awt.Color(0, 0, 0));
        update.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("update");
        update.setOpaque(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        add(update);
        update.setBounds(553, 0, 90, 40);

        delete.setBackground(new java.awt.Color(0, 0, 0));
        delete.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("delete");
        delete.setOpaque(false);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        add(delete);
        delete.setBounds(653, 0, 90, 40);

        end.setBackground(new java.awt.Color(0, 0, 0));
        end.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        end.setForeground(new java.awt.Color(255, 255, 255));
        end.setText("end");
        end.setOpaque(false);
        add(end);
        end.setBounds(350, 0, 90, 40);

        date.setBackground(new java.awt.Color(0, 0, 0));
        date.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setText("date");
        date.setOpaque(false);
        add(date);
        date.setBounds(130, 0, 90, 40);

        seats.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        seats.setForeground(new java.awt.Color(255, 255, 255));
        seats.setText("jLabel2");
        add(seats);
        seats.setBounds(460, 0, 60, 40);

        start.setBackground(new java.awt.Color(0, 0, 0));
        start.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        start.setForeground(new java.awt.Color(255, 255, 255));
        start.setText("start");
        start.setOpaque(false);
        add(start);
        start.setBounds(230, 0, 100, 40);

        hall.setBackground(new java.awt.Color(0, 0, 0));
        hall.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        hall.setForeground(new java.awt.Color(255, 255, 255));
        hall.setText("1");
        hall.setOpaque(false);
        add(hall);
        hall.setBounds(0, 0, 120, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinema/img/bk.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(-190, 0, 1180, 760);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
       
        time.deleteTime(time.getId());
        TimeFrame.admin();
    }//GEN-LAST:event_deleteActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
      if(time.checkTime(Integer.parseInt(start.getText().substring(0,2)),Integer.parseInt(end.getText().substring(0,2)) ,date.getText(),time.getHallId())){
        
        time.UpdateTime(time.getId(), movie.getId(),date.getText()+dt,st+start.getText()+st1, nd+end.getText()+nd1,Integer.parseInt(hall.getText()));
       new Box("Time updated",0);
       TimeFrame.admin();}
      else new Box("a movie within the givin time alredy exist");
    }//GEN-LAST:event_updateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField date;
    private javax.swing.JButton delete;
    private javax.swing.JTextField end;
    private javax.swing.JTextField hall;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel seats;
    private javax.swing.JTextField start;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
