/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinema;

/**
 *
 * @author SuPeR_FaNtASy
 */
public class STime extends javax.swing.JPanel {
Movie m;
    Time time;
    public STime() {
        initComponents();
        bookbtn.setVisible(false);
    }
      public STime(Time time,Movie m) {
          this.time=time;
          this.m=m;
        initComponents();
        booklbl.setVisible(false);
          
        
        
        
        
        hall.setText("      "+time.getHallId()+"");
        date.setText(time.getMovieDate().substring(0, 10));
        end.setText(time.getMovieEnd().substring(11,16));
        start.setText(time.getMovieStart().substring(11,16));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hall = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        start = new javax.swing.JLabel();
        booklbl = new javax.swing.JLabel();
        end = new javax.swing.JLabel();
        bookbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        hall.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        hall.setForeground(new java.awt.Color(255, 255, 255));
        hall.setText("  hall no ");
        add(hall);
        hall.setBounds(10, 0, 100, 40);

        date.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setText("Date ");
        add(date);
        date.setBounds(160, 0, 120, 40);

        start.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        start.setForeground(new java.awt.Color(255, 255, 255));
        start.setText("start time");
        add(start);
        start.setBounds(290, 0, 90, 40);

        booklbl.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        booklbl.setForeground(new java.awt.Color(255, 255, 255));
        booklbl.setText("click here to book");
        add(booklbl);
        booklbl.setBounds(570, 0, 140, 40);

        end.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        end.setForeground(new java.awt.Color(255, 255, 255));
        end.setText("end time");
        add(end);
        end.setBounds(440, 0, 80, 40);

        bookbtn.setBackground(new java.awt.Color(0, 0, 0));
        bookbtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        bookbtn.setForeground(new java.awt.Color(255, 255, 255));
        bookbtn.setText("Book");
        bookbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bookbtn.setOpaque(false);
        bookbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookbtnActionPerformed(evt);
            }
        });
        add(bookbtn);
        bookbtn.setBounds(550, 0, 180, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinema/img/bk.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(-190, 0, 1180, 760);
    }// </editor-fold>//GEN-END:initComponents

    private void bookbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookbtnActionPerformed
        new SeatsFrame(time,m);
    }//GEN-LAST:event_bookbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookbtn;
    private javax.swing.JLabel booklbl;
    private javax.swing.JLabel date;
    private javax.swing.JLabel end;
    private javax.swing.JLabel hall;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel start;
    // End of variables declaration//GEN-END:variables
}
